version: "3.9"

services:
  backend:
    image: my-webgis-app:latest
    container_name: uvicorn-app
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: >
      sh -c "python manage.py migrate &&
             uvicorn WebGIS.asgi:application --host 0.0.0.0 --port 8000 --workers 3"
    environment:
          - DJANGO_SETTINGS_MODULE=WebGIS.settings
    volumes:
      - ./static:/app/staticfiles
    expose:
      - "8000"
    env_file:
      - .env.local
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgis/postgis:15-3.3
    container_name: postgis_db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env.local
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend-proxy:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "8001:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/static:ro
    depends_on:
      backend:
        condition: service_started

volumes:
  postgres_data:
